// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/mine/go-playground/src/c_go/hello.go:1:1
package main

import _ "unsafe"

import "fmt"

// 用go实现SayHello也是可以的（c++,其他语言都可以）
//
//export SayHello
func SayHello(s * /*line :10:18*/_Ctype_char /*line :10:24*/) {
	fmt.Print(( /*line :11:12*/_Cfunc_GoString /*line :11:21*/)(s))
}
